"""Sandbox + venv + credential management for Agent 5.

This module is the canonical owner of:
  * Per-candidate sandbox directory naming (``candidate_slug``)
  * Virtual-environment creation + race-safe locking
    (``acquire_venv_lock``, ``create_venv``, ``venv_python_path``)
  * Pre-creation of venvs in parallel (``precreate_venvs_for_candidates``)
  * Pre-install of common HTTP/audio dependencies (``preinstall_venv_deps``)
  * Credential resolution from registry + env vars (``resolve_credentials``,
    ``resolve_candidate_credentials``)
  * Env-var name extraction from harness source (``extract_env_vars_from_code``)
  * Env-var similarity scoring (``env_var_similarity``)
  * Sandbox env var assembly (``build_sandbox_env`` — re-exported from
    ``agent5.tools``)

The ``puzzleeval.agents.implement_test_env`` legacy module re-exports every
public name here so source-grep tests + external callers keep working.

Critical invariants (R2 from the plan's risk register):
  * ``_VENV_CREATE_LOCKS`` and ``_VENV_CREATE_LOCKS_GUARD`` are MODULE-LEVEL
    state. Every caller MUST resolve to the SAME dict object — otherwise
    two threads can race for the same sandbox dir and the lock fails to
    serialize. The legacy ``implement_test_env._VENV_CREATE_LOCKS`` name
    is bound to ``sandbox._VENV_CREATE_LOCKS`` via a re-export shim, NOT
    re-declared. Do not redeclare these in any other module.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import TYPE_CHECKING, Any

from puzzleeval.provider_registry import _normalize

if TYPE_CHECKING:
    from puzzleeval.schemas import Agent5Input, ScreenedCandidate, TestHarness


# ---------------------------------------------------------------------------
# VENV_PREINSTALL_MANIFEST — packages every harness needs
# ---------------------------------------------------------------------------
# Pre-installed into the venv right after creation. Saves 2-3 Agent 5 turns
# the builder would otherwise spend on `pip install requests` etc.
VENV_PREINSTALL_MANIFEST: list[str] = [
    "requests>=2.31.0",          # HTTP client — every REST harness
    "websocket-client>=1.6.0",   # sync WS — OpenAI Realtime, ElevenLabs
    "pydub>=0.25.1",             # audio format conversion (MP3/WAV/PCM16)
    "soundfile>=0.12.1",         # PCM16 I/O without ffmpeg dependency
    "numpy>=1.26.0",             # array math (pydub dep + audio pipelines)
    "python-dotenv>=1.0.0",      # env loading (common for candidate keys)
]


# ---------------------------------------------------------------------------
# Harness forensics shim — auto-injected into every sandbox
# ---------------------------------------------------------------------------
# Every harness imports `_forensics` for the universal observability API
# (log + traced_op + canonical event taxonomy + auto-hooks for common
# HTTP/WS libs + credential redaction + faulthandler stack-dump-on-hang).
#
# The shim is staged ONCE per sandbox at venv-creation time. It uses
# stdlib-only for the universal API + best-effort optional library hooks
# (each hook in its own try/except — one library's failure doesn't affect
# others or the universal API).
#
# The shim runs in the harness subprocess (different venv than the parent).
# Config is passed via env vars set by the parent's build_sandbox_env.
#
# The semantic verification gate (verify_forensics_coverage in
# agent5/verification.py) enforces that every harness imports _forensics
# first, wraps SDK calls in traced_op, and instruments session/stream
# lifecycle for streaming harnesses.
FORENSICS_SHIM_CONTENT = '''"""Auto-injected forensics layer for PuzzleEval harnesses.

DO NOT EDIT — this file is generated by puzzleeval.agents.agent5.sandbox.

Universal observability API every harness uses:
  * log(event, **kw)             — record a canonical event
  * traced_op(op, **kw)          — context manager: auto-pairs op_start/op_done/op_error
  * log_thread_start(name, **kw) — for background threads (auto-called by Thread.start hook)
  * log_thread_error(name, error, **kw) — for thread errors (auto-called by Thread.run hook)

JSONL output: ``harness_forensics.jsonl`` in the sandbox root.

Auto-instrumentation (best-effort, fail-soft — each hook in its own try/except):
  * requests.Session.request                     — sync HTTP
  * httpx.Client.send / AsyncClient.send         — modern HTTP (sync + async)
  * aiohttp.ClientSession._request               — async HTTP
  * websocket.WebSocket.send/recv                — sync WebSocket (websocket-client)
  * websockets.WebSocketClientProtocol.send/recv — async WebSocket
  * threading.Thread.start/run                   — auto-emit thread_start + thread_error

Anything else (provider SDKs, gRPC, raw sockets, async tasks, custom clients)
must be wrapped manually with traced_op() or log() calls. The verifier checks
for this.

Credential redaction is MANDATORY — Authorization, xi-api-key, Bearer tokens,
?token=, ?signature=, ?api_key= are stripped from URLs and headers BEFORE
serialization.
"""

from __future__ import annotations

import atexit
import contextlib
import faulthandler
import json
import os
import re
import sys
import threading
import time
import traceback


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------

_LOG_PATH = os.environ.get("PUZZLEEVAL_HARNESS_LOG") or "harness_forensics.jsonl"
_T0 = time.monotonic()
_LOCK = threading.Lock()

# Rate-limit: at most this many events per second. Excess events drop with a
# log_throttled summary so a runaway loop can\\'t fill the disk or log file.
_RATE_LIMIT_PER_SEC = 100
_window_start = time.monotonic()
_window_count = 0
_dropped_in_window = 0


# ---------------------------------------------------------------------------
# Credential redaction — MANDATORY before any field hits disk
# ---------------------------------------------------------------------------

_CREDENTIAL_HEADERS = frozenset({
    "authorization", "x-api-key", "xi-api-key", "x-auth-token",
    "openai-api-key", "anthropic-api-key", "x-goog-api-key",
    "bearer", "cookie", "set-cookie",
})

_QUERY_PARAM_REDACT = re.compile(
    r"([?&](?:token|signature|api[_-]?key|access[_-]?token|"
    r"id[_-]?token|key|secret|password|sig)=)[^&#]*",
    re.IGNORECASE,
)


def _redact_url(url):
    """Strip credentials from URL query string. Hostname preserved."""
    if not isinstance(url, str):
        return url
    return _QUERY_PARAM_REDACT.sub(r"\\1[REDACTED]", url)


def _url_host(url):
    """Extract hostname only — never expose path or query params in events."""
    if not isinstance(url, str):
        return None
    # Cheap parser: scheme://host/...  or  scheme://host?...
    m = re.match(r"^[a-zA-Z]+://([^/?#]+)", url)
    return m.group(1) if m else None


def _redact_headers(headers):
    """Replace credential header values with [REDACTED]."""
    if not headers:
        return headers
    try:
        out = {}
        for k, v in dict(headers).items():
            if k.lower() in _CREDENTIAL_HEADERS:
                out[k] = "[REDACTED]"
            elif isinstance(v, str) and v.lower().startswith("bearer "):
                out[k] = "Bearer [REDACTED]"
            else:
                out[k] = v
        return out
    except Exception:
        return "[redaction-failed]"


def _redact_record(record):
    """Walk a record and redact any URL or header field. Mutates in place."""
    if not isinstance(record, dict):
        return record
    if "url" in record:
        record["url"] = _redact_url(record["url"])
    if "headers" in record:
        record["headers"] = _redact_headers(record["headers"])
    return record


# ---------------------------------------------------------------------------
# Core emitter — single chokepoint for all events
# ---------------------------------------------------------------------------

def _emit(record):
    """Append one record to harness_forensics.jsonl. Thread-safe + rate-limited."""
    global _window_start, _window_count, _dropped_in_window

    record["t_ms"] = round((time.monotonic() - _T0) * 1000, 1)
    record["t_abs"] = time.time()
    _redact_record(record)

    with _LOCK:
        now = time.monotonic()
        if now - _window_start >= 1.0:
            # Window roll: emit drop summary if any
            if _dropped_in_window > 0:
                drop_record = {
                    "kind": "event",
                    "event": "log_throttled",
                    "dropped": _dropped_in_window,
                    "t_ms": round((now - _T0) * 1000, 1),
                    "t_abs": time.time(),
                }
                try:
                    with open(_LOG_PATH, "a", encoding="utf-8") as f:
                        f.write(json.dumps(drop_record, default=str) + "\\n")
                except OSError:
                    pass
            _window_start = now
            _window_count = 0
            _dropped_in_window = 0

        if _window_count >= _RATE_LIMIT_PER_SEC:
            _dropped_in_window += 1
            return
        _window_count += 1

        try:
            with open(_LOG_PATH, "a", encoding="utf-8") as f:
                f.write(json.dumps(record, default=str) + "\\n")
        except OSError:
            # Don\\'t crash the harness if the log file isn\\'t writable.
            pass


# ---------------------------------------------------------------------------
# Public API — log() + traced_op() + thread helpers
# ---------------------------------------------------------------------------

def log(event, **kw):
    """Record a canonical event.

    Use canonical event names from the OBSERVABILITY CONTRACT:
      - harness_start, harness_exit
      - session_create_start/done/error
      - request_start/done/error
      - stream_start/event/done/error
      - thread_start/error
      - timeout, provider_error

    Standard fields per event:
      - op (snake_case operation name; builder picks)
      - provider (short tag: "elevenlabs", "openai", "deepgram", ...)
      - url_host (hostname only — NEVER full URL, NEVER query params)
      - status_code, duration_ms, attempt, request_id, error_type, error
    """
    record = {"kind": "event", "event": event}
    record.update(kw)
    _emit(record)


class traced_op:
    """Context manager: auto-pairs op_start/op_done/op_error with timing.

        with traced_op("create_session", provider="elevenlabs"):
            agent_id = create_agent(api_key)

    On entry: emits {event: "op_start", op: "<name>", **kw}
    On clean exit: emits {event: "op_done", op: "<name>", duration_ms, **kw}
    On exception: emits {event: "op_error", op: "<name>", duration_ms,
                          error_type, error, **kw}; re-raises.

    For canonical-taxonomy events (session_create_start, request_done,
    stream_event, etc.), call ``log()`` directly — those are domain-event
    names, distinct from this wrapper pattern. The verifier accepts both:
    it scans the source for ``log("<name>"`` AND ``traced_op("<name>"``
    calls when checking session/stream lifecycle coverage.
    """

    __slots__ = ("op", "kw", "_t0")

    def __init__(self, op, **kw):
        self.op = op
        self.kw = kw
        self._t0 = None

    def __enter__(self):
        self._t0 = time.monotonic()
        record = {
            "kind": "event",
            "event": "op_start",
            "op": self.op,
        }
        record.update(self.kw)
        _emit(record)
        return self

    def __exit__(self, exc_type, exc, tb):
        duration_ms = round((time.monotonic() - self._t0) * 1000, 1)
        if exc is None:
            record = {
                "kind": "event",
                "event": "op_done",
                "op": self.op,
                "duration_ms": duration_ms,
            }
        else:
            record = {
                "kind": "event",
                "event": "op_error",
                "op": self.op,
                "duration_ms": duration_ms,
                "error_type": type(exc).__name__,
                "error": str(exc)[:200],
            }
        record.update(self.kw)
        _emit(record)
        return False  # never swallow exceptions


def log_thread_start(name, **kw):
    """Record a background thread starting."""
    record = {"kind": "thread", "event": "thread_start", "name": name,
              "tid": threading.get_ident()}
    record.update(kw)
    _emit(record)


def log_thread_error(name, error, **kw):
    """Record an uncaught exception in a background thread."""
    record = {
        "kind": "thread",
        "event": "thread_error",
        "name": name,
        "tid": threading.get_ident(),
        "error_type": type(error).__name__ if isinstance(error, BaseException) else "Error",
        "error": str(error)[:200],
        "tb": traceback.format_exc()[:1000],
    }
    record.update(kw)
    _emit(record)


# ---------------------------------------------------------------------------
# Auto-instrumentation — best-effort, fail-soft, default ON
# ---------------------------------------------------------------------------

def _install_requests_hook():
    try:
        import requests
        orig = requests.Session.request
        if getattr(orig, "_puzzleeval_traced", False):
            return
        def traced(self, method, url, **kw):
            t0 = time.monotonic()
            host = _url_host(url)
            try:
                r = orig(self, method, url, **kw)
                _emit({"kind": "http", "event": "request_done",
                       "method": method, "url_host": host,
                       "status_code": r.status_code,
                       "duration_ms": round((time.monotonic()-t0)*1000, 1)})
                return r
            except Exception as exc:
                _emit({"kind": "http", "event": "request_error",
                       "method": method, "url_host": host,
                       "duration_ms": round((time.monotonic()-t0)*1000, 1),
                       "error_type": type(exc).__name__,
                       "error": str(exc)[:200]})
                raise
        traced._puzzleeval_traced = True
        requests.Session.request = traced
    except Exception:
        pass


def _install_httpx_hook():
    try:
        import httpx
        # Sync client
        try:
            orig_send = httpx.Client.send
            if not getattr(orig_send, "_puzzleeval_traced", False):
                def traced_send(self, request, **kw):
                    t0 = time.monotonic()
                    host = _url_host(str(request.url))
                    try:
                        r = orig_send(self, request, **kw)
                        _emit({"kind": "http", "event": "request_done",
                               "method": request.method, "url_host": host,
                               "status_code": r.status_code,
                               "duration_ms": round((time.monotonic()-t0)*1000, 1)})
                        return r
                    except Exception as exc:
                        _emit({"kind": "http", "event": "request_error",
                               "method": request.method, "url_host": host,
                               "duration_ms": round((time.monotonic()-t0)*1000, 1),
                               "error_type": type(exc).__name__,
                               "error": str(exc)[:200]})
                        raise
                traced_send._puzzleeval_traced = True
                httpx.Client.send = traced_send
        except Exception:
            pass
        # Async client
        try:
            orig_async_send = httpx.AsyncClient.send
            if not getattr(orig_async_send, "_puzzleeval_traced", False):
                async def traced_async_send(self, request, **kw):
                    t0 = time.monotonic()
                    host = _url_host(str(request.url))
                    try:
                        r = await orig_async_send(self, request, **kw)
                        _emit({"kind": "http", "event": "request_done",
                               "method": request.method, "url_host": host,
                               "status_code": r.status_code,
                               "duration_ms": round((time.monotonic()-t0)*1000, 1)})
                        return r
                    except Exception as exc:
                        _emit({"kind": "http", "event": "request_error",
                               "method": request.method, "url_host": host,
                               "duration_ms": round((time.monotonic()-t0)*1000, 1),
                               "error_type": type(exc).__name__,
                               "error": str(exc)[:200]})
                        raise
                traced_async_send._puzzleeval_traced = True
                httpx.AsyncClient.send = traced_async_send
        except Exception:
            pass
    except Exception:
        pass


def _install_aiohttp_hook():
    try:
        import aiohttp
        orig = aiohttp.ClientSession._request
        if getattr(orig, "_puzzleeval_traced", False):
            return
        async def traced(self, method, str_or_url, **kw):
            t0 = time.monotonic()
            host = _url_host(str(str_or_url))
            try:
                r = await orig(self, method, str_or_url, **kw)
                _emit({"kind": "http", "event": "request_done",
                       "method": method, "url_host": host,
                       "status_code": r.status,
                       "duration_ms": round((time.monotonic()-t0)*1000, 1)})
                return r
            except Exception as exc:
                _emit({"kind": "http", "event": "request_error",
                       "method": method, "url_host": host,
                       "duration_ms": round((time.monotonic()-t0)*1000, 1),
                       "error_type": type(exc).__name__,
                       "error": str(exc)[:200]})
                raise
        traced._puzzleeval_traced = True
        aiohttp.ClientSession._request = traced
    except Exception:
        pass


def _install_websocket_client_hook():
    try:
        import websocket
        # send
        orig_send = websocket.WebSocket.send
        if not getattr(orig_send, "_puzzleeval_traced", False):
            def traced_send(self, payload, *a, **k):
                try:
                    msg_type = "?"
                    if isinstance(payload, str):
                        try:
                            msg_type = json.loads(payload).get("type", "?")
                        except Exception:
                            pass
                    elif isinstance(payload, (bytes, bytearray)):
                        msg_type = "binary"
                    _emit({"kind": "ws", "event": "stream_event", "dir": "send",
                           "type": msg_type,
                           "bytes": len(payload) if payload else 0})
                except Exception:
                    pass
                return orig_send(self, payload, *a, **k)
            traced_send._puzzleeval_traced = True
            websocket.WebSocket.send = traced_send
        # recv
        orig_recv = websocket.WebSocket.recv
        if not getattr(orig_recv, "_puzzleeval_traced", False):
            def traced_recv(self):
                r = orig_recv(self)
                try:
                    msg_type = "?"
                    if isinstance(r, str):
                        try:
                            msg_type = json.loads(r).get("type", "?")
                        except Exception:
                            pass
                    elif isinstance(r, (bytes, bytearray)):
                        msg_type = "binary"
                    _emit({"kind": "ws", "event": "stream_event", "dir": "recv",
                           "type": msg_type, "bytes": len(r) if r else 0})
                except Exception:
                    pass
                return r
            traced_recv._puzzleeval_traced = True
            websocket.WebSocket.recv = traced_recv
    except Exception:
        pass


def _install_websockets_hook():
    try:
        import websockets
        # The websockets library moved its client class around across versions;
        # try the common locations and bail silently if none match.
        targets = []
        try:
            from websockets.legacy.client import WebSocketClientProtocol as _Legacy
            targets.append(_Legacy)
        except Exception:
            pass
        try:
            from websockets.client import ClientConnection as _New
            targets.append(_New)
        except Exception:
            pass
        for cls in targets:
            try:
                orig_send = cls.send
                if getattr(orig_send, "_puzzleeval_traced", False):
                    continue
                async def traced_send(self, message, *a, **k):
                    try:
                        msg_type = "?"
                        if isinstance(message, str):
                            try:
                                msg_type = json.loads(message).get("type", "?")
                            except Exception:
                                pass
                        elif isinstance(message, (bytes, bytearray)):
                            msg_type = "binary"
                        _emit({"kind": "ws", "event": "stream_event",
                               "dir": "send", "type": msg_type,
                               "bytes": len(message) if message else 0})
                    except Exception:
                        pass
                    return await orig_send(self, message, *a, **k)
                traced_send._puzzleeval_traced = True
                cls.send = traced_send
            except Exception:
                pass
    except Exception:
        pass


def _install_threading_hook():
    """Auto-emit thread_start on Thread.start() + thread_error on uncaught."""
    try:
        orig_start = threading.Thread.start
        if getattr(orig_start, "_puzzleeval_traced", False):
            return

        def traced_start(self):
            try:
                _emit({"kind": "thread", "event": "thread_start",
                       "name": getattr(self, "name", "?")})
            except Exception:
                pass
            return orig_start(self)
        traced_start._puzzleeval_traced = True
        threading.Thread.start = traced_start

        orig_run = threading.Thread.run
        def traced_run(self):
            try:
                return orig_run(self)
            except BaseException as exc:
                try:
                    log_thread_error(getattr(self, "name", "?"), exc)
                except Exception:
                    pass
                raise
        traced_run._puzzleeval_traced = True
        threading.Thread.run = traced_run
    except Exception:
        pass


def _install_all_hooks():
    """Install every hook. Each in its own try/except — one failure doesn\\'t affect others."""
    _install_requests_hook()
    _install_httpx_hook()
    _install_aiohttp_hook()
    _install_websocket_client_hook()
    _install_websockets_hook()
    _install_threading_hook()


# ---------------------------------------------------------------------------
# Faulthandler stack-dump-on-hang
# ---------------------------------------------------------------------------

def _install_faulthandler():
    """Print full stack trace to stderr if any thread hangs > N seconds.

    Disabled when PUZZLEEVAL_HARNESS_FAULTHANDLER_TIMEOUT=0.
    """
    try:
        timeout = int(os.environ.get("PUZZLEEVAL_HARNESS_FAULTHANDLER_TIMEOUT", "45"))
        if timeout > 0:
            faulthandler.dump_traceback_later(timeout, repeat=True, file=sys.stderr)
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Final flush
# ---------------------------------------------------------------------------

@atexit.register
def _final_flush():
    try:
        _emit({"kind": "event", "event": "harness_exit", "pid": os.getpid()})
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Bootstrap — runs on import
# ---------------------------------------------------------------------------

_install_all_hooks()
_install_faulthandler()
log("harness_start", pid=os.getpid())


__all__ = [
    "log", "traced_op", "log_thread_start", "log_thread_error",
]
'''


def stage_forensics_shim(sandbox_dir: Path) -> bool:
    """Write `_forensics.py` into the sandbox root.

    Idempotent: re-running just rewrites the file with the same content.
    Safe to call from create_venv (post-venv) AND from precreate paths.

    Returns True on success; False on OSError (logged but never raises —
    forensics is best-effort, harness still runs).
    """
    target = sandbox_dir / "_forensics.py"
    try:
        sandbox_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(FORENSICS_SHIM_CONTENT, encoding="utf-8")
        return True
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Per-sandbox lock registry — race-safe venv creation
# ---------------------------------------------------------------------------
# Both ``precreate_venvs_for_candidates`` (background, post-selection) and
# ``create_venv`` (synchronous, called from Agent 5 build) can race for the
# same sandbox dir if Agent 4 finishes fast and Agent 5 starts before
# pre-creation completes. The per-sandbox-dir lock ensures whichever call
# gets there first does the work; the other short-circuits when it sees
# the venv python already exists.
#
# CRITICAL: this dict is module-level state. Every caller (sandbox.py,
# implement_test_env.py, pipeline_runner.py) MUST resolve to the SAME
# object. Test ``test_venv_lock_dict_singleton_across_modules_after_move``
# enforces this invariant.
_VENV_CREATE_LOCKS: dict[str, threading.Lock] = {}
_VENV_CREATE_LOCKS_GUARD = threading.Lock()


def candidate_slug(name: str) -> str:
    """Convert a candidate name to a filesystem-safe directory name.

    "Google Document AI" → "google_document_ai"
    "AWS Textract (OCR)" → "aws_textract_ocr"
    """
    slug = name.lower()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    slug = slug.strip("_")
    return slug[:40]


def acquire_venv_lock(sandbox_dir: Path) -> threading.Lock:
    """Get-or-create the per-sandbox venv-creation lock.

    Two callers passing the SAME sandbox_dir get the SAME lock object.
    Different sandbox dirs get different locks (no cross-candidate
    contention).
    """
    key = str(sandbox_dir.resolve())
    with _VENV_CREATE_LOCKS_GUARD:
        lock = _VENV_CREATE_LOCKS.get(key)
        if lock is None:
            lock = threading.Lock()
            _VENV_CREATE_LOCKS[key] = lock
        return lock


def venv_python_path(venv_dir: Path) -> Path:
    """Return the platform-correct path to the venv's python interpreter."""
    if sys.platform == "win32":
        return venv_dir / "Scripts" / "python.exe"
    return venv_dir / "bin" / "python"


def create_venv(
    sandbox_dir: Path,
    logger,
    trace_id: str,
    candidate_name: str,
) -> bool:
    """Create a Python venv in the sandbox directory. Returns True on success.

    The venv is at sandbox_dir/.venv. Commands run via ``run_code()``
    will automatically use it (via ``build_sandbox_env()`` PATH injection).

    After the venv is created, we pre-install ``VENV_PREINSTALL_MANIFEST``
    (small, widely-used HTTP/audio deps). This is best-effort — pre-install
    failures do NOT fail venv creation. Controlled by
    ``PUZZLEEVAL_VENV_PREINSTALL=0`` to disable (debug / minimal-venv runs).

    **Idempotent + race-safe**: when the venv already exists (pre-created
    by ``precreate_venvs_for_candidates`` during Agent 4), short-circuits
    after acquiring the per-sandbox lock. When two callers race for the
    same sandbox, the second one waits, sees the venv exists, and
    short-circuits — no duplicate work, no concurrent pip install.
    """
    venv_dir = sandbox_dir / ".venv"
    vpython = venv_python_path(venv_dir)
    lock = acquire_venv_lock(sandbox_dir)
    with lock:
        if vpython.exists():
            logger.info(
                f"Venv already exists for {candidate_name} — short-circuit",
                extra={
                    "operation": "venv_create_short_circuit",
                    "trace_id": trace_id,
                    "candidate_name": candidate_name,
                    "venv_dir": str(venv_dir),
                },
            )
            # Stage forensics shim if missing (covers sandboxes pre-created
            # before this change OR cases where the shim got deleted).
            if not (sandbox_dir / "_forensics.py").exists():
                stage_forensics_shim(sandbox_dir)
            return True
        try:
            # `python -m venv .venv` includes pip by default. On
            # Windows+anaconda this can silently fail — the venv's
            # python.exe exists but `python -m pip` returns "No module
            # named pip" (real-run trace 8ded6706). Defense: after
            # creation, verify pip actually landed and run ensurepip
            # as a fallback if not.
            result = subprocess.run(
                [sys.executable, "-m", "venv", str(venv_dir)],
                capture_output=True,
                text=True,
                timeout=120,
            )
            if result.returncode == 0:
                # Verify pip actually landed in the venv (Windows+anaconda
                # edge case fix).
                pip_check = subprocess.run(
                    [str(vpython), "-m", "pip", "--version"],
                    capture_output=True, text=True, timeout=15,
                )
                if pip_check.returncode != 0:
                    logger.warning(
                        f"Venv created for {candidate_name} but pip missing — "
                        "bootstrapping via ensurepip",
                        extra={
                            "operation": "venv_pip_missing_ensurepip",
                            "trace_id": trace_id,
                            "candidate_name": candidate_name,
                            "pip_check_stderr": (pip_check.stderr or "")[:300],
                        },
                    )
                    # Best-effort ensurepip — don't fail venv creation
                    subprocess.run(
                        [str(vpython), "-m", "ensurepip", "--upgrade", "--default-pip"],
                        capture_output=True, text=True, timeout=30,
                    )
                logger.info(f"Venv created for {candidate_name}", extra={
                    "operation": "venv_create",
                    "trace_id": trace_id,
                    "candidate_name": candidate_name,
                    "venv_dir": str(venv_dir),
                })
                # Stage the forensics shim immediately after venv creation
                # so it's present before the builder writes any harness code.
                # Best-effort — failures are logged but don't fail venv creation.
                shim_ok = stage_forensics_shim(sandbox_dir)
                if not shim_ok:
                    logger.warning(
                        f"forensics shim staging failed for {candidate_name} "
                        f"(harness will run without observability)",
                        extra={
                            "operation": "forensics_stage_failed",
                            "trace_id": trace_id,
                            "candidate_name": candidate_name,
                        },
                    )
                if os.environ.get("PUZZLEEVAL_VENV_PREINSTALL", "1") != "0":
                    preinstall_venv_deps(venv_dir, logger, trace_id, candidate_name)
                return True
            else:
                logger.warning(
                    f"Venv creation failed for {candidate_name}: {result.stderr[:500]}",
                    extra={
                        "operation": "venv_create_failed",
                        "trace_id": trace_id,
                        "candidate_name": candidate_name,
                    },
                )
                return False
        except (subprocess.TimeoutExpired, OSError) as e:
            logger.warning(f"Venv creation error for {candidate_name}: {e}", extra={
                "operation": "venv_create_error",
                "trace_id": trace_id,
                "candidate_name": candidate_name,
            })
            return False


def precreate_venvs_for_candidates(
    candidate_names: list[str],
    trace_id: str,
    logger,
    runs_root: "Path | str | None" = None,
    max_workers: int | None = None,
) -> dict[str, bool]:
    """Pre-create venvs for SELECTED candidates in parallel.

    Hook for pipeline_runner: called immediately after the user submits
    Phase 6 selections (or after Phase 7 auto-pick), running concurrently
    with Agent 4 verification. Each candidate's venv lives at the same
    path Agent 5 expects — so when Agent 5 calls ``create_venv`` later,
    it short-circuits via the lock-guarded existence check.

    Saves 60-120s of Agent 5's build wall-clock per candidate by moving
    venv create + ``pip install`` of ``VENV_PREINSTALL_MANIFEST`` into
    the Agent 4 phase's natural slack.

    **Only runs for SELECTED candidates** — pass the post-selection
    filtered name list. Non-selected Agent 2 candidates never get venvs.

    Returns a dict mapping ``candidate_name → success bool``. Failures
    are logged but never raise — Agent 5's ``create_venv`` falls back to
    creating the venv synchronously (legacy path) when a candidate's
    pre-creation didn't complete.
    """
    from puzzleeval.web_doc_cache import candidate_sandbox_dir

    if not candidate_names:
        return {}
    workers = max_workers if max_workers is not None else min(len(candidate_names), 5)
    workers = max(1, workers)

    logger.info(
        f"Pre-creating venvs for {len(candidate_names)} selected candidate(s)",
        extra={
            "operation": "venv_precreate_start",
            "trace_id": trace_id,
            "candidate_count": len(candidate_names),
            "workers": workers,
        },
    )

    results: dict[str, bool] = {}

    def _create_one(name: str) -> tuple[str, bool]:
        try:
            sandbox_dir = candidate_sandbox_dir(trace_id, name, runs_root=runs_root)
            sandbox_dir.mkdir(parents=True, exist_ok=True)
            ok = create_venv(sandbox_dir, logger, trace_id, name)
            return name, ok
        except Exception as exc:  # noqa: BLE001 — must never crash background task
            logger.warning(
                f"venv pre-create exception for {name}: "
                f"{type(exc).__name__}: {exc}",
                extra={
                    "operation": "venv_precreate_exception",
                    "trace_id": trace_id,
                    "candidate_name": name,
                    "error_type": type(exc).__name__,
                    "error_msg": str(exc)[:300],
                },
            )
            return name, False

    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = [executor.submit(_create_one, name) for name in candidate_names]
        for future in as_completed(futures):
            name, ok = future.result()
            results[name] = ok

    succeeded = sum(1 for v in results.values() if v)
    logger.info(
        f"Pre-create complete: {succeeded}/{len(results)} venvs ready",
        extra={
            "operation": "venv_precreate_complete",
            "trace_id": trace_id,
            "succeeded": succeeded,
            "total": len(results),
        },
    )
    return results


def preinstall_venv_deps(
    venv_dir: Path,
    logger,
    trace_id: str,
    candidate_name: str,
) -> None:
    """Best-effort pre-install of common harness deps into a fresh venv.

    Runs ``python -m pip install --quiet <manifest>`` using the venv's
    interpreter. Timeouts at 180s (accommodates slow networks). Logs
    success/failure but never raises — the builder is still responsible
    for writing requirements.txt with any candidate-specific extras, and
    missing packages would surface in the builder's own env_check turn.
    """
    vpython = venv_python_path(venv_dir)
    if not vpython.exists():
        logger.warning(
            f"venv python not found for pre-install: {vpython}",
            extra={"operation": "venv_preinstall_missing_python",
                   "trace_id": trace_id,
                   "candidate_name": candidate_name},
        )
        return
    try:
        result = subprocess.run(
            [str(vpython), "-m", "pip", "install", "--quiet",
             "--disable-pip-version-check", *VENV_PREINSTALL_MANIFEST],
            capture_output=True,
            text=True,
            timeout=180,
        )
        if result.returncode == 0:
            logger.info(
                f"Pre-installed {len(VENV_PREINSTALL_MANIFEST)} deps "
                f"for {candidate_name}",
                extra={"operation": "venv_preinstall_ok",
                       "trace_id": trace_id,
                       "candidate_name": candidate_name,
                       "packages": VENV_PREINSTALL_MANIFEST},
            )
        else:
            logger.info(
                f"Pre-install partial for {candidate_name}: "
                f"{result.stderr[:400]}",
                extra={"operation": "venv_preinstall_partial",
                       "trace_id": trace_id,
                       "candidate_name": candidate_name},
            )
    except (subprocess.TimeoutExpired, OSError) as exc:
        logger.info(
            f"Pre-install failed for {candidate_name} (non-fatal): {exc}",
            extra={"operation": "venv_preinstall_error",
                   "trace_id": trace_id,
                   "candidate_name": candidate_name},
        )


def build_sandbox_env(sandbox_dir: Path, extra_env: dict[str, str] | None = None) -> dict:
    """Build environment variables for subprocess execution in the sandbox.

    Re-exports from ``agent5.tools.build_sandbox_env`` so callers have one
    canonical home for sandbox-related helpers.
    """
    from puzzleeval.agents.agent5 import tools as _tools
    return _tools.build_sandbox_env(sandbox_dir, extra_env)


# ---------------------------------------------------------------------------
# Credential resolution
# ---------------------------------------------------------------------------

def resolve_credentials(
    input_data: "Agent5Input",
    candidate: "ScreenedCandidate",
    provider_slug: str,
) -> dict[str, str] | None:
    """Resolve credentials for a candidate from registry or env vars.

    Used during Agent 5 build setup. Tries provider_credentials registry
    first (matched by normalized candidate or provider name), falls back
    to scanning env vars for matching auth-shaped names.
    """
    credentials = None

    if input_data.provider_credentials:
        norm_provider = _normalize(candidate.provider)
        norm_candidate = _normalize(candidate.name)
        credentials = (
            input_data.provider_credentials.get(norm_candidate)
            or input_data.provider_credentials.get(norm_provider)
        )

    if not credentials:
        possible_vars = [f"{provider_slug}_API_KEY"]
        # Also try to extract from any existing harness code
        sandbox_path = (
            Path("runs") / input_data.trace_id
            / "harnesses" / candidate_slug(candidate.name)
        )
        harness_code = _read_harness_code(sandbox_path)
        if harness_code:
            possible_vars.extend(extract_env_vars_from_code(harness_code))

        env_creds: dict[str, str] = {}
        for var in possible_vars:
            val = os.environ.get(var)
            if val:
                env_creds[var] = val
        if env_creds:
            credentials = env_creds

    return credentials


def resolve_candidate_credentials(
    harness: "TestHarness",
    provider_credentials: dict[str, dict[str, str]] | None,
) -> dict[str, str] | None:
    """Resolve credentials for a candidate at test-execution time.

    A candidate can use multiple providers (e.g., an "ElevenLabs Voice
    Stack" harness calls ElevenLabs for TTS + OpenAI Whisper for STT +
    Anthropic Claude for reasoning). Historically this resolver
    short-circuited on the first registry-key match and returned only
    one provider's env vars — harnesses that needed cross-provider keys
    got KeyError on the others.

    General fix: union EVERY registered provider whose normalized key
    appears anywhere in the candidate's searchable surface — name,
    provider, validation_notes. "elevenlabs voice stack" pulls
    ElevenLabs AND OpenAI AND Anthropic when all three are mentioned in
    the candidate's description.

    Env-var fallback (harness.auth_env_vars) still fills in any key
    that wasn't provided via the registry — unchanged.
    """
    credentials: dict[str, str] = {}

    if provider_credentials:
        searchable_parts = [
            getattr(harness, "candidate_name", "") or "",
            getattr(harness, "provider", "") or "",
            getattr(harness, "validation_notes", "") or "",
        ]
        searchable = " ".join(searchable_parts).lower()
        candidate_key = harness.candidate_name.lower().strip()
        provider_key = harness.provider.lower().strip()

        for registry_key, env_dict in provider_credentials.items():
            norm_key = registry_key.lower().strip()
            if not norm_key:
                continue
            if (
                norm_key == candidate_key
                or norm_key == provider_key
                or norm_key in candidate_key
                or candidate_key in norm_key
                or norm_key in provider_key
                or provider_key in norm_key
                or norm_key in searchable  # cross-provider mention match
            ):
                credentials.update(env_dict)
                # Don't break — union ALL matching providers

    if harness.auth_env_vars:
        for var_name in harness.auth_env_vars:
            if var_name not in credentials:
                env_val = os.environ.get(var_name)
                if env_val:
                    credentials[var_name] = env_val

    return credentials if credentials else None


def _read_harness_code(sandbox_dir: Path) -> str | None:
    """Read harness.py from sandbox if it exists."""
    harness_file = sandbox_dir / "harness.py"
    if harness_file.exists():
        try:
            return harness_file.read_text(encoding="utf-8")
        except OSError:
            return None
    return None


def extract_env_vars_from_code(code: str) -> list[str]:
    """Parse harness.py source code to find environment variable names
    used via os.environ.get() or os.environ[].

    Returns a deduplicated, ORDER-PRESERVED list of env var names that
    look like auth-related credentials (containing KEY, TOKEN, SECRET,
    ID, PASSWORD, AUTH, CREDENTIAL, REALM). Ignores generic vars like
    PYTHONDONTWRITEBYTECODE.
    """
    if not code:
        return []

    pattern = r'os\.environ(?:\.get)?\s*[\(\[]\s*["\']([A-Z][A-Z0-9_]*)["\']'
    matches = re.findall(pattern, code)

    auth_keywords = {"KEY", "TOKEN", "SECRET", "ID", "PASSWORD", "AUTH", "CREDENTIAL", "REALM"}
    auth_vars = [v for v in matches if any(kw in v for kw in auth_keywords)]

    seen: set[str] = set()
    result: list[str] = []
    for var in auth_vars:
        if var not in seen:
            seen.add(var)
            result.append(var)
    return result


def env_var_similarity(a: str, b: str) -> float:
    """Compute similarity between two normalized env var names.

    Uses longest common substring ratio. Returns 0.0-1.0.

    "NANONETSAPIKEY" vs "NANONETSINAPIKEY" → high similarity
    "NANONETSAPIKEY" vs "OPENAIKEY" → low similarity
    """
    if not a or not b:
        return 0.0
    shorter, longer = (a, b) if len(a) <= len(b) else (b, a)
    best = 0
    for i in range(len(shorter)):
        for j in range(i + 3, len(shorter) + 1):  # min substring length 3
            if shorter[i:j] in longer:
                best = max(best, j - i)
    return best / max(len(a), len(b))


__all__ = [
    # Constants
    "VENV_PREINSTALL_MANIFEST",
    # Sandbox naming
    "candidate_slug",
    # Venv management
    "acquire_venv_lock",
    "venv_python_path",
    "create_venv",
    "precreate_venvs_for_candidates",
    "preinstall_venv_deps",
    # Sandbox env
    "build_sandbox_env",
    # Credential resolution
    "resolve_credentials",
    "resolve_candidate_credentials",
    "extract_env_vars_from_code",
    "env_var_similarity",
]
