# ============================================================================
# Agent 1 — Fast Intent Classifier (Haiku, ~3-5s)
# ============================================================================
# PURPOSE:
#   Decide on every chat turn whether the user has given enough info for the
#   pipeline to start (concrete sub-task + domain) and produce ONE of:
#     - is_clear=True  → 1-2 sentence acknowledgement; the heavy Agent 1
#                        planner runs in the background as the first step
#                        of the pipeline.
#     - is_clear=False → 1-3 specific clarifying questions targeting the
#                        missing critical fact.
#
# WHY SPLIT FROM run_user_understanding_agent (the planner):
#   The planner has to emit a full Agent1Result — WorkflowBlueprint with
#   step DAG + TestPlan with per-scope test specs + sub_tasks + domain +
#   keywords. That's 60+ structured fields generated by Opus 4.7 with
#   adaptive thinking — naturally 30-60s. The user can't see "starting
#   pipeline" until that finishes, which felt like the system was hung.
#
#   This classifier just answers "ready or not, and what's the human-
#   facing message?" — three fields. Haiku 4.5 returns it in ~3-5s. The
#   chat handler ships the ack to the browser, which transitions to the
#   pipeline view and shows "Designing workflow architecture…" while the
#   planner runs in run_pipeline's first step.
# ============================================================================

from __future__ import annotations

import time
from typing import Any

import anthropic

from puzzleeval.config import (
    ANTHROPIC_API_KEY,
    MAX_TOKENS,
)
from puzzleeval.exceptions import (
    AgentAPIError,
    AgentOutputError,
    AgentRateLimitError,
)
from puzzleeval.logging_setup import get_logger, log_llm_call
from puzzleeval.schemas import Agent1Input, Agent1IntentResult


# Haiku 4.5 — small enough for ~3-5s response on a multi-turn classifier
# task. Override via PUZZLEEVAL_AGENT1_INTENT_MODEL if you want to test
# a different model (e.g., Sonnet for nuanced classification).
import os
INTENT_CLASSIFIER_MODEL = os.environ.get(
    "PUZZLEEVAL_AGENT1_INTENT_MODEL",
    "claude-haiku-4-5-20251001",
)

# Cheap classifier — keep token budget tight. The output is at most a
# 2-sentence ack + 3 short questions.
INTENT_MAX_TOKENS = int(os.environ.get(
    "PUZZLEEVAL_AGENT1_INTENT_MAX_TOKENS", "800",
))


SYSTEM_PROMPT = """You are the front-of-house for PuzzleEval, an AI agent evaluation platform. You decide on each turn whether the user has told us enough for the pipeline to start designing AI solutions, AND you write the user-facing chat message.

You produce THREE fields and nothing else:

1. `is_clear` (bool) — true iff the user has given BOTH:
   - A CONCRETE sub-task with a testable input→output behavior
     (e.g., "OCR invoice photos and extract vendor + line items + total"
            or "voice agent that takes pickup orders for my coffee shop")
   - A BUSINESS DOMAIN (infer from context — "coffee shop" → food-service,
     "invoices" → accounting, "phone calls" → customer-support; only ask
     if truly ambiguous)

   Set `is_clear=true` even when optional info is missing (budget,
   technical level, integrations, monthly volume). The downstream planner
   uses sensible defaults for those.

2. `assistant_message` (string) — the EXACT text the user sees in chat.
   - When is_clear=true: a 1-2 sentence acknowledgement that names what
     you understood. Examples:
       "Got it — voice phone agent for Bean & Brew handling FAQs (hours, menu, pricing) and pickup orders. Designing the workflow now…"
       "On it — invoice OCR for a home repair business extracting vendor, line items, and totals. Designing the workflow now…"
     End with "Designing the workflow now…" or "Starting now…" so the
     user knows real work is happening.
   - When is_clear=false: a short conversational lead-in (1 sentence)
     that precedes the clarifying_questions. Example:
       "Happy to help — a few quick details so the search hits the right tools:"

3. `clarifying_questions` (list[string]) — empty when is_clear=true.
   When is_clear=false, 1-3 SPECIFIC questions about CRITICAL info only:
   - "What documents are you processing? (invoices, receipts, contracts, etc.)"
   - "What output do you need? (structured fields, plain text, summary)"
   NEVER ask about budget, technical level, monthly volume, or
   integrations — those are optional and the planner uses defaults.

## Critical rules

- Be DECISIVE. If the user has clear sub-task + domain, set is_clear=true
  immediately even on turn 1. Don't ask follow-ups when you don't need them.
- The acknowledgement is the user's only signal that work is starting.
  Make it specific to THEIR ask, not generic ("Got it!" alone is bad).
- Keep messages short. The user is waiting for the pipeline page to open.
- Do NOT design the workflow, list candidates, mention test plans, or
  describe what the pipeline will do. The downstream planner owns that.
- When the user uploaded a file (you'll see "User uploaded N file(s)" in
  context), treat the file as adding context — set is_clear=true unless
  their text is also unclear.

## Examples

User: "I need OCR for invoices in my home repair business — extract vendor, line items, totals."
→ is_clear=true
→ assistant_message: "Got it — invoice OCR for a home repair business extracting vendor, line items, and totals. Designing the workflow now…"
→ clarifying_questions: []

User: "I want an AI thing for my business."
→ is_clear=false
→ assistant_message: "Happy to help — a couple quick details so the search hits the right tools:"
→ clarifying_questions: ["What does the AI need to DO? (e.g., answer phone calls, extract data from documents, classify support emails)", "What kind of business is this? (helps me find domain-specific tools)"]

User: "Voice agent for my coffee shop. Takes orders, answers FAQ."
→ is_clear=true
→ assistant_message: "On it — voice phone agent for a coffee shop handling FAQs and pickup orders. Designing the workflow now…"
→ clarifying_questions: []
"""


def _build_messages(
    user_text: str,
    conversation_history: list[dict[str, Any]] | None,
) -> list[dict[str, Any]]:
    """Assemble the messages array — same shape the planner uses."""
    messages: list[dict[str, Any]] = []
    if conversation_history:
        messages.extend(conversation_history)
    messages.append({"role": "user", "content": user_text})
    return messages


def run_intent_classifier(input_data: Agent1Input) -> Agent1IntentResult:
    """Run the fast intent classifier (Haiku 4.5).

    Returns Agent1IntentResult with is_clear + assistant_message +
    clarifying_questions in ~3-5s. The chat handler ships the result
    to the browser immediately. When is_clear=True, the orchestrator
    kicks off run_pipeline whose first step calls
    ``run_user_understanding_agent`` (the heavy planner) to populate
    state.agent1_result before Agent 2 starts.
    """
    from puzzleeval.anthropic_client import build_client
    client = build_client(api_key=ANTHROPIC_API_KEY)

    logger = get_logger("agent_1_intent_classifier")
    logger.info("Agent 1 intent classifier started", extra={
        "operation": "agent_start", "trace_id": input_data.trace_id,
    })

    # File-content note. The classifier doesn't read full file content —
    # the planner does. We only tell the classifier "user uploaded N
    # files" so it can lean toward is_clear=True when the user's text
    # alone might be ambiguous but the file fills the gap.
    user_text = input_data.user_text
    if input_data.workflow_file_path:
        user_text = (
            f"[User uploaded a workflow document at "
            f"{input_data.workflow_file_path}; full content available "
            f"to the planner.]\n\n{user_text}"
        )
    if input_data.additional_context and not input_data.conversation_history:
        user_text += f"\n\nAdditional context:\n{input_data.additional_context}"

    messages = _build_messages(
        user_text=user_text,
        conversation_history=input_data.conversation_history,
    )

    start_time = time.time()
    try:
        from puzzleeval.structured_output import parse_with_fallback
        # The classifier output is small (3 fields, ~150 tokens). Strict
        # grammar would compile fine, but parity with the planner —
        # which uses prefer_non_strict to skip a doomed roundtrip — is
        # not the question here. Just run strict (fast) and let the
        # fallback catch validation issues.
        response = parse_with_fallback(
            client=client,
            model=INTENT_CLASSIFIER_MODEL,
            max_tokens=INTENT_MAX_TOKENS,
            system=[{"type": "text", "text": SYSTEM_PROMPT}],
            messages=messages,
            output_format=Agent1IntentResult,
            extra={},
            trace_id=input_data.trace_id,
        )
    except anthropic.RateLimitError as e:
        logger.error("Rate limit hit (intent classifier)", extra={
            "operation": "llm_call", "trace_id": input_data.trace_id,
            "error": str(e), "error_type": "RateLimitError",
        })
        raise AgentRateLimitError(
            message=f"Rate limit exceeded (intent classifier): {e}",
            agent_name="agent_1_intent", trace_id=input_data.trace_id,
        )
    except anthropic.APIConnectionError as e:
        logger.error("API connection failed (intent classifier)", extra={
            "operation": "llm_call", "trace_id": input_data.trace_id,
            "error": str(e), "error_type": "APIConnectionError",
        })
        raise AgentAPIError(
            message=f"Failed to connect to Anthropic API (intent classifier): {e}",
            agent_name="agent_1_intent", trace_id=input_data.trace_id,
        )
    except anthropic.APIStatusError as e:
        logger.error("API error (intent classifier)", extra={
            "operation": "llm_call", "trace_id": input_data.trace_id,
            "error": str(e), "error_type": "APIStatusError",
        })
        raise AgentAPIError(
            message=f"Anthropic API error (intent classifier): {e}",
            agent_name="agent_1_intent", trace_id=input_data.trace_id,
        )

    call_cost = log_llm_call(
        logger=logger,
        response=response,
        model=INTENT_CLASSIFIER_MODEL,
        trace_id=input_data.trace_id,
        start_time=start_time,
        operation="agent_1_intent",
    )

    result = response.parsed_output
    if result is None:
        logger.error("Intent classifier returned no parsed output", extra={
            "operation": "output_validation", "trace_id": input_data.trace_id,
            "stop_reason": response.stop_reason,
        })
        raise AgentOutputError(
            message=(
                f"Intent classifier returned no parsed output. "
                f"stop_reason={response.stop_reason}"
            ),
            agent_name="agent_1_intent",
            trace_id=input_data.trace_id,
        )

    result.cost_usd = call_cost
    logger.info("Agent 1 intent classifier completed", extra={
        "operation": "agent_complete",
        "trace_id": input_data.trace_id,
        "is_clear": result.is_clear,
    })
    return result


__all__ = [
    "INTENT_CLASSIFIER_MODEL",
    "SYSTEM_PROMPT",
    "run_intent_classifier",
]
